version: "3"
services:
  backend:
    container_name: backend
    image: node:16.13.1
    volumes:
      - ./packages/backend:/usr/src/service
    working_dir: /usr/src/service
    command: ["npm", "run", "populate"]
    ports:
      - "4000:4000"
    depends_on:
      - mongo-courses
  mongo-courses:
    container_name: mongo-courses
    image: mongo
    volumes:
      - ./mongo-db:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: none
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
