[package]
name = "relay_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.18"
actix-cors = "0.6.0-beta.8"
futures = "0.3"
env_logger = "0.9"
serde = "1.0.103"
serde_json = "1.0.44"
serde_derive = "1.0.103"
juniper = "0.15.7"
juniper_actix = "0.4.0"
mongodb ="2.0.0"
bson = "2.0.0"
base64 = "0.13.0"
bcrypt = "0.10"
jsonwebtoken = "7"
tokio = "1.15.0"

[[bin]]
name = "relay_rust"
path = "src/main.rs"