version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm ci
  build:
    commands:
      - echo Running tests...
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`
